
Vagrant.configure('2') do |config|

  config.vm.define "hack-for-sweden" do |config|

    config.vm.box = 'ubuntu/xenial64'

    config.vm.provider :digital_ocean do |provider, override|
      override.ssh.private_key_path = './.ssh/id_rsa'
      override.vm.box = 'digital_ocean'
      override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
      provider.token = '0f729e24d80d6ea4c5083f2ff9bbf8c51c0b2f8ce7ed7e00ebcbc86b7f87fd6d'
      provider.image = 'ubuntu-16-04-x64'
      provider.region = 'ams3'
      provider.size = '512mb'
    end

    config.vm.synced_folder '.', '/data'

    # Provision docker host with GCP credentials
    config.vm.provision "shell", inline: <<-SHELL
      mkdir -p /etc/systemd/system/docker.service.d/

      echo "[Service]" > /etc/systemd/system/docker.service.d/gcp-credentials.conf
      echo "Environment=\"GOOGLE_APPLICATION_CREDENTIALS=/data/.gcp/filiplindqvist-com-e0b61f4cb4a7.json\"" >> /etc/systemd/system/docker.service.d/gcp-credentials.conf
      echo "" >> /etc/systemd/system/docker.service.d/gcp-credentials.conf

    SHELL

    config.vm.network "forwarded_port", guest: 80, host: 8080

  end

end