
# Read env file
SECRETS=IO.read('./.env').split(/\n/).map{|s| s.split(/=/)}.to_h

Vagrant.configure('2') do |config|

  config.vm.define "hack-for-sweden" do |config|

    config.vm.box = 'ubuntu/xenial64'

    config.vm.provider :digital_ocean do |provider, override|
      override.ssh.private_key_path = './.ssh/id_rsa'
      override.vm.box = 'digital_ocean'
      override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
      provider.token = SECRETS['DIGITAL_OCEAN_TOKEN']
      provider.image = 'ubuntu-16-04-x64'
      provider.region = 'ams3'
      provider.size = '2gb'
    end

    config.vm.synced_folder '.', '/data'

    # Provision docker host with GCP credentials
    config.vm.provision "shell", inline: <<-SHELL
      mkdir -p /etc/systemd/system/docker.service.d/

      echo "[Service]" > /etc/systemd/system/docker.service.d/gcp-credentials.conf
      echo "Environment=\"GOOGLE_APPLICATION_CREDENTIALS=/data/.gcp/filiplindqvist-com-e0b61f4cb4a7.json\"" >> /etc/systemd/system/docker.service.d/gcp-credentials.conf
      echo "" >> /etc/systemd/system/docker.service.d/gcp-credentials.conf

      curl -sSL https://agent.digitalocean.com/install.sh | sh

      curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
      sudo apt-get install -y nodejs

      npm install -g pm2
      sudo apt-get install -y build-essential

      (cd /data && npm install && pm2 start app.js --watch)

    SHELL

    config.vm.network "forwarded_port", guest: 80, host: 8080

  end

end
